#!/bin/sh -x

if [ ! -f /etc/config/smstools3 ]; then
        touch /etc/config/smstools3
		touch /etc/smstools3.user
		touch /etc/smstools3.pb
        uci add smstools3 sms
	uci add smstools3 root_phone
	uci commit smstools3
fi
