# SPDX-License-Identifier: Apache-2.0
#

include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=LuCI app for QiYou Game Booster
LUCI_DEPENDS:=+qiyougamebooster
LUCI_PKGARCH:=all

PKG_MAINTAINER:=qiyouacc, Internet1235

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
