#!/bin/sh /etc/rc.common

# NueXini

START=99

on()
{
	uci set dhcp.@dnsmasq[0].filter_aaaa='1'
	uci commit dhcp
	
	echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
	
	/etc/init.d/odhcpd disable >/dev/null 2>&1
	
	uci set network.@device[0].ipv6='0' >/dev/null 2>&1
	uci set network.@device[1].ipv6='0' >/dev/null 2>&1
	uci set network.@device[2].ipv6='0' >/dev/null 2>&1
	uci commit network
}

off()
{
	uci set dhcp.@dnsmasq[0].filter_aaaa='0'
	uci commit dhcp
	
	/etc/init.d/odhcpd enable >/dev/null 2>&1
	
	uci del network.@device[0].ipv6 >/dev/null 2>&1
	uci del network.@device[1].ipv6 >/dev/null 2>&1
	uci del network.@device[2].ipv6 >/dev/null 2>&1
	uci commit network
}

onoff()
{
	local enable
	config_get_bool enable $1 enable
	
	sed -i '/disable_ipv6/d' /etc/sysctl.conf >/dev/null 2>&1
	
	if [ $enable = 0 ]; then
		off
	else
		on
	fi
	
	sysctl -p /etc/sysctl.conf >/dev/null 2>&1
	
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

start()
{
	config_load disableipv6
	config_foreach onoff onoff
}

stop()
{
	return 0
}

