#!/bin/sh /etc/rc.common
# NueXini

START=20

start()
{
	stop
	enable=$(uci get disableipv6.@onoff[0].enable)
	[ $enable -eq 0 ] && exit 0
	uci set dhcp.@dnsmasq[0].filter_aaaa='1'
	uci commit dhcp
	cat /etc/sysctl.conf | grep -q 'disable_ipv6 = 1' && exit 0
	echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
	sysctl -p /etc/sysctl.conf
}

stop()
{
	uci set dhcp.@dnsmasq[0].filter_aaaa='0'
	uci commit dhcp
	sed -i '/disable_ipv6/d' /etc/sysctl.conf
	sysctl -p /etc/sysctl.conf
}

