#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Teleofis >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Teleofis=/luci-static/teleofis
		set luci.main.mediaurlbase=/luci-static/teleofis
		commit luci
	EOF
fi

exit 0
