#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Routerich >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Routerich=/luci-static/routerich
		set luci.main.mediaurlbase=/luci-static/routerich
		commit luci
	EOF
fi

exit 0
