#!/bin/sh

SECTIONS=$(echo $(uci show modeminfo | awk -F [\]\[\@=] '/=modeminfo/{print $3}'))

for s in $SECTIONS; do
	if [ -f /tmp/modem${s}device ]; then
		CURFAM=$(cat /tmp/modem${s}device)
	else
		CURFAM=GENERIC
	fi
	FAM=$(uci -q get modeminfo.@modeminfo[${s}].family)
	if [ "$FAM" != "$CURFAM" ]; then
		rm -rf /tmp/modem${s}device
		uci delete modeminfo.@modeminfo[${s}].family
		uci commit
	fi
done
