#!/bin/sh

SECTIONS=$(echo $(uci show ttl | awk -F [\]\[\@=] '/=ttl/{print $3}'))
TTLENABLE=0

get_vars(){
	for v in iface enable;  do
		eval $v=$(uci -q get ttl.@ttl[${s}].${v} 2>/dev/nul)
	done
}

for s in $SECTIONS; do
	if [ "$s" ]; then
		get_vars
	else
		exit 0
	fi
	if [ $INTERFACE = $iface ]; then
		TTLENABLE=1
		break
	fi
done

if [ "$TTLENABLE" = "1" ]; then
	/etc/init.d/ttl reload
fi
