#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@unblockneteasemusic[-1]
	add ucitrack unblockneteasemusic
	set ucitrack.@unblockneteasemusic[-1].init=unblockneteasemusic
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
