#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@disableipv6[-1]
	add ucitrack disableipv6
	set ucitrack.@disableipv6[-1].init=disableipv6
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
