include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cellled
LUCI_DEPENDS:=+cellled
PKG_VERSION:=0.1.0
PKG_RELEASE:=2
LUCI_TITLE:=LuCI application for showing cellular RSSI LED

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
