
# NueXini

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-disableipv6
PKG_VERSION:=1.0
PKG_RELEASE:=20220614

LUCI_TITLE:=LuCI Support for disableipv6
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature