
# NueXini

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-disableipv6
PKG_VERSION:=2022.08.12
PKG_RELEASE:=1

LUCI_URL:=https://github.com/NueXini/NueXini_Packages
LUCI_MAINTAINER:=NueXini

LUCI_TITLE:=LuCI Support for disableipv6
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature