#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service(){
	logger -t "MMconfig" "MMConfig started"
}

reload_service(){
	/usr/share/modeminfo/mmconfig
}

service_triggers() {
	procd_add_reload_trigger mmconfig
}
