#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Luci for PS3NETSRV
LUCI_DEPENDS:=+ps3netsrv
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-ps3netsrv
PKG_VERSION:=1
PKG_RELEASE:=2

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
