#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Lightblue >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Lightblue=/luci-static/lightblue
		set luci.main.mediaurlbase=/luci-static/lightblue
		commit luci
	EOF
fi

exit 0
