ipv4:
  enable: true
  gettype: url
  url: https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net
  netinterface: br-lan
  domains:
  - ""
ipv6:
  enable: false
  gettype: url
  url: https://myip6.ipip.net, https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me
  netinterface: ""
  ipv6reg: ""
  domains:
  - ""
dns:
  name: alidns
  id: ""
  secret: ""
user:
  username: ""
  password: ""
webhook:
  webhookurl: ""
  webhookrequestbody: ""
notallowwanaccess: true
ttl: ""
