#!/bin/sh /etc/rc.common
USE_PROCD=1

START=90
STOP=10

enabled="$(uci get nezha-agent.config.enabled)"
tls="$(uci get nezha-agent.config.tls)"
host="$(uci get nezha-agent.config.host)"
secret="$(uci get nezha-agent.config.secret)"

start_service() {
        [ "$enabled" == "1" ] || exit 0
        procd_open_instance
        if [ "$tls" == "1" ]
        then
                procd_set_param command /usr/bin/nezha-agent -s "${host}" -p "${secret}" -d --tls
        else
                procd_set_param command /usr/bin/nezha-agent -s "${host}" -p "${secret}" -d
        fi
        procd_set_param respawn
        [ -e /proc/sys/kernel/core_pattern ] && {
                procd_set_param limits core="unlimited"
        }
        procd_close_instance
}

reload_service() {
  stop
  start
}