include $(TOPDIR)/rules.mk

LUCI_TITLE:=MWAN3 Ledhelper simple webUI
LUCI_DEPENDS:=+luci-app-mwan3 +mwan3-ledhelper
PKG_LICENSE:=GPLv3
PKG_VERSION:=0.0.1
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
