#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	touch /etc/config/atinout
	uci set atinout.general=atinout
fi

if [ ! -f /etc/atcommands.user  ]; then
	echo "Demo command \"ATI\";ATI" > /etc/atcommands.user
fi

rm -rf /tmp/luci-*
