#!/bin/sh /etc/rc.common
# Copyright (C) 2020 IrineSistiana
# shellcheck disable=SC2034,SC3043

START=99
USE_PROCD=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/usr/bin/mosdns                        # where is mosdns
RES_DIR=/etc/mosdns/                        # resource dir / working dir / the dir where you store ip/domain lists
CONF=$(uci -q get mosdns.mosdns.configfile) # where is the config file, it can be a relative path to $RES_DIR
CRON_FILE=/etc/crontabs/root
#####  ONLY CHANGE THIS BLOCK  ######

inital_conf() {
  config_load "mosdns"
  config_get "enabled" "mosdns" "enabled" "0"
}

service_triggers() {
  procd_add_reload_trigger "mosdns"
}

restore_setting() {
  sed -i "/list server/d" /etc/config/dhcp
  uci set dhcp.@dnsmasq[0].noresolv='0'
  uci del dhcp.@dnsmasq[0].cachesize
  uci set dhcp.@dnsmasq[0].filter_aaaa='1'
  uci del dhcp.@dnsmasq[0].setbymosdns
  uci commit dhcp
}

prepare_setting() {
  redirect=$(uci -q get mosdns.mosdns.redirect)
  if [ "$redirect" = "1" ]; then
    sed -i "/list server/d" /etc/config/dhcp
    uci add_list dhcp.@dnsmasq[0].server="127.0.0.1#$(uci -q get mosdns.mosdns.listen_port)"
    uci set dhcp.@dnsmasq[0].rebind_protection='0'
    uci set dhcp.@dnsmasq[0].noresolv="1"
    uci set dhcp.@dnsmasq[0].cachesize='0'
    uci set dhcp.@dnsmasq[0].filter_aaaa='0'
    uci set dhcp.@dnsmasq[0].setbymosdns='1'
    uci commit dhcp
  fi
}

restart_others() {
  /etc/init.d/network reload
  /etc/init.d/dnsmasq reload
}

reload_service() {
  stop
  sleep 2s
  printf "MosDNS is restarted!\n"
  start
}

setcron() {
  touch "$CRON_FILE"
  sed -i '/mosdns.sh/d' "$CRON_FILE" 2>/dev/null
  if [ "$(uci -q get mosdns.mosdns.geo_auto_update)" = "1" ]; then
    echo "0 $(uci -q get mosdns.mosdns.geo_update_day_time) * * $(uci -q get mosdns.mosdns.geo_update_week_time) /usr/share/mosdns/mosdns.sh update_mosdns" >>"$CRON_FILE"
  fi
  crontab "$CRON_FILE"
}

delcron() {
  sed -i '/mosdns.sh/d' "$CRON_FILE" 2>/dev/null
  crontab "$CRON_FILE"
}

adblock() {
  local mosdns_adblock
  local serverlist_act="/etc/mosdns/rule/serverlist.act"
  local serverlist_txt="/etc/mosdns/rule/serverlist.txt"
  mosdns_adblock=$(uci -q get mosdns.mosdns.adblock)

  if [ "$mosdns_adblock" != "0" ]; then
    if [ ! -L "$serverlist_act" ] || [ "$(readlink -f "$serverlist_act")" != "$serverlist_txt" ]; then
      ln -sf "$serverlist_txt" "$serverlist_act" || {
        echo "Failed to create symbolic link."
        return 1
      }
    fi
  else
    if [ ! -L "$serverlist_act" ] || [ "$(readlink -f "$serverlist_act")" != "/dev/null" ]; then
      ln -sf /dev/null "$serverlist_act" || {
        echo "Failed to create symbolic link."
        return 1
      }
    fi
  fi
}

v4config() {
  rm -rf /etc/mosdns/def_config.yaml
  cp -rf /usr/share/mosdns/def_config_orig.yaml /etc/mosdns/def_config.yaml
  sed -i "s,listenport,$(uci -q get mosdns.mosdns.listen_port),g" /etc/mosdns/def_config.yaml
  sed -i "s,loglvl,$(uci -q get mosdns.mosdns.loglv),g" /etc/mosdns/def_config.yaml
  sed -i "s,logfile,$(uci -q get mosdns.mosdns.logfile),g" /etc/mosdns/def_config.yaml
  sed -i "s,remotedns1,$(uci -q get mosdns.mosdns.remote_dns1),g" /etc/mosdns/def_config.yaml
  sed -i "s,remotedns2,$(uci -q get mosdns.mosdns.remote_dns2),g" /etc/mosdns/def_config.yaml
  sed -i "s,localdns1,$(/usr/share/mosdns/mosdns.sh dns 0),g" /etc/mosdns/def_config.yaml
  sed -i "s,localdns2,$(/usr/share/mosdns/mosdns.sh dns 1),g" /etc/mosdns/def_config.yaml
}

start_service() {
  # Reading config
  local enabled=""
  inital_conf
  if [ "$enabled" = "0" ]; then
    printf "MosDNS has been turned off\n"
    return 1
  fi
  delcron
  setcron
  adblock
  true >"$(/usr/share/mosdns/mosdns.sh logfile)"
  sysctl -w net.core.rmem_max=2500000
  v4config
  procd_open_instance mosdns
  procd_set_param command "$PROG" start -d "$RES_DIR" -c "$CONF"
  procd_set_param user root
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_close_instance mosdns

  if [ "$(uci -q get mosdns.mosdns.configfile)" = "./def_config.yaml" ]; then
    restore_setting
    prepare_setting
    if [ "$(uci -q get mosdns.mosdns.redirect)" = "1" ] && [ "$(uci -q get shadowsocksr.@global[0].run_mode)" != gfw ]; then
      true >/etc/ssrplus/gfw_list.conf
      sed -i '/update.lua/d' /usr/share/shadowsocksr/ssrplusupdate.sh
      sed -i '/bin\/sh/a\/usr/bin/lua /usr/share/shadowsocksr/update.lua ad_data' /usr/share/shadowsocksr/ssrplusupdate.sh
      sed -i '/bin\/sh/a\/usr/bin/lua /usr/share/shadowsocksr/update.lua nfip_data' /usr/share/shadowsocksr/ssrplusupdate.sh
      sed -i '/bin\/sh/a\/usr/bin/lua /usr/share/shadowsocksr/update.lua ip_data' /usr/share/shadowsocksr/ssrplusupdate.sh
    fi
    restart_others
  fi

  printf "MosDNS turned on\n"
  printf "enabled=%d\n" "$enabled"
}

stop_service() {
  local enabled=""
  inital_conf
  pgrep -f /usr/bin/mosdns | xargs kill -9
  if [ "$(uci -q get mosdns.mosdns.configfile)" = "./def_config.yaml" ]; then
    if [ "$enabled" = "0" ] && [ "$(uci -q get dhcp.@dnsmasq[0].setbymosdns)" = "1" ]; then
      restore_setting
    fi
    restart_others
  fi
  delcron
  printf "MosDNS turned off\n"
  printf "enabled=%d\n" "$enabled"
}
