#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for Dnsforwarder
LUCI_DEPENDS:=+dnsforwarder
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-dnsforwarder
PKG_VERSION:=3.0.0
PKG_RELEASE:=1

PKG_LICENSE:=GPL-3.0
PKG_MAINTAINER:=Dennis <openwrt@tossp.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
