#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service(){
	/usr/share/ttl.sh
	logger -t "TTL" "TTL reload"
}

reload_service(){
	sleep 10 && start &
}

service_triggers() {
	procd_add_reload_trigger ttl
}
